// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace producaoWeb.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20240814122217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Funcao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("salario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Funcoes");
                });

            modelBuilder.Entity("Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("funcaoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("funcaoId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Pessoa", b =>
                {
                    b.HasOne("Funcao", "funcao")
                        .WithMany()
                        .HasForeignKey("funcaoId");

                    b.Navigation("funcao");
                });
#pragma warning restore 612, 618
        }
    }
}
